// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU6vWya3a6eNLHJ6LH6T4JM50vWtxF5Oc',
    appId: '1:556289902663:web:757f68e799b7b87fc74962',
    messagingSenderId: '556289902663',
    projectId: 'galihiot',
    authDomain: 'galihiot.firebaseapp.com',
    storageBucket: 'galihiot.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApj6uEdsG_qfTtbi04y98ftUF-Wjsx6qw',
    appId: '1:556289902663:android:63d3b6cf1d0343e3c74962',
    messagingSenderId: '556289902663',
    projectId: 'galihiot',
    storageBucket: 'galihiot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCufP9vn7KNkHn4UpijtO7Qs196EqHiR0',
    appId: '1:556289902663:ios:949cb8fe35476250c74962',
    messagingSenderId: '556289902663',
    projectId: 'galihiot',
    storageBucket: 'galihiot.firebasestorage.app',
    iosBundleId: 'com.example.coba1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCufP9vn7KNkHn4UpijtO7Qs196EqHiR0',
    appId: '1:556289902663:ios:949cb8fe35476250c74962',
    messagingSenderId: '556289902663',
    projectId: 'galihiot',
    storageBucket: 'galihiot.firebasestorage.app',
    iosBundleId: 'com.example.coba1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU6vWya3a6eNLHJ6LH6T4JM50vWtxF5Oc',
    appId: '1:556289902663:web:14e84c53ad03e3a3c74962',
    messagingSenderId: '556289902663',
    projectId: 'galihiot',
    authDomain: 'galihiot.firebaseapp.com',
    storageBucket: 'galihiot.firebasestorage.app',
  );

}